### ISSUE TITLE
language server error

### ISSUE THREAD

**Issue by gdkrmr** [JuliaEditorSupport/julia-vscode#252]
I have a couple of errors regarding VSCode on Ubuntu 16.04, probably not all of them belong here, see also [here](https://discourse.julialang.org/t/vs-code-extension-v0-7-released/5284/4)

- The repository is often unavailable
- The julia language server keeps crashing.
- I have files in my home folder which I use for quick testing, e.g. ~/test.jl and when I open them VSCode tries to parse everything in my home folder and consumes a lot of cpu time for a very long time, the VSCode process consumes ~ 130% cpu constantly.

**Comment by gdkrmr** [comment]
This is what I get in the `output` window, I shortened it, it seems that the language server wants to access a directory it is not supposed to:
```
...
INFO: parsed /.../.../...
...

ERROR: LoadError: SystemError: unable to read directory /home/gkraemer/.cache/dconf: Permission denied
Stacktrace:
 [1] try_yieldto(::Base.##296#297{Task}, ::Task) at ./event.jl:189
 [2] wait() at ./event.jl:234
 [3] take_unbuffered(::Channel{Any}) at ./channels.jl:340
 [4] take!(::Channel{Any}) at ./channels.jl:317
 [5] done(::Channel{Any}, ::Base.ChannelIterState{Any}) at ./channels.jl:406
 [6] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at /home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:41
 [7] run(::LanguageServer.LanguageServerInstance) at /home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:52
 [8] include_from_node1(::String) at ./loading.jl:569
 [9] include(::String) at ./sysimg.jl:14
 [10] process_options(::Base.JLOptions) at ./client.jl:305
 [11] _start() at ./client.jl:371
while loading /home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 3:40:04 PM] Connection to server got closed. Server will restart.
[Error - 3:40:04 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-jsonrpc/lib/main.js:816:25)
    at Object.dispose (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-languageclient/lib/client.js:66:35)
    at LanguageClient.handleConnectionClosed (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-languageclient/lib/client.js:1071:38)
    at LanguageClient.handleConnectionClosed (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-languageclient/lib/main.js:86:15)
    at closeHandler (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-languageclient/lib/client.js:1059:18)
    at CallbackList.invoke (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/home/gkraemer/.vscode/extensions/julialang.language-julia-0.7.0/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 3:40:04 PM] Request textDocument/documentLink failed.
...
```

**Comment by gdkrmr** [comment]
The process 
```
code /usr/share/code/resources/app/out/bootstrap --type=watcherService
```
is guilty of the high cpu consumption.

**Comment by davidanthoff** [comment]
> The repository is often unavailable

What do you mean by that? What repository are you referring to?

> The julia language server keeps crashing.

Does that just happen when you open your home folder, or also in other situations? If it does happen in other situations, can you post a log of those crashes? Ideally as a new issue.

> I have files in my home folder which I use for quick testing, e.g. ~/test.jl and when I open them VSCode tries to parse everything in my home folder and consumes a lot of cpu time for a very long time, the VSCode process consumes ~ 130% cpu constantly.

VS Code has this idea that if you open a folder, the language services should analyze all the files in that folder. If you open your home folder, that is probably killing it. I *think* when you just open one file in your home folder, isn't there a way for VS Code to not also open the whole folder? But in general maybe we should just disable the language server if we detect that someone is opening the home folder...

**Comment by gdkrmr** [comment]
> 
> 
>     The repository is often unavailable
> 
> What do you mean by that? What repository are you referring to?
> 

https://packages.microsoft.com/repos/vscode

the VSCode repository for ubuntu, there is probably nothing you can do about it.

>     The julia language server keeps crashing.
> 
> Does that just happen when you open your home folder, or also in other situations? If it does happen in other situations, can you post a log of those crashes? Ideally as a new issue.

I tried opening a small folder, and it seemed to work fine. Where do I get a log from? I already posted most of the output buffer above, from there I suppose the reason for the crash is that there is some file that the language server has no permissions to open.
 
>     I have files in my home folder which I use for quick testing, e.g. ~/test.jl and when I open them VSCode tries to parse everything in my home folder and consumes a lot of cpu time for a very long time, the VSCode process consumes ~ 130% cpu constantly.
> 
> VS Code has this idea that if you open a folder, the language services should analyze all the files in that folder. If you open your home folder, that is probably killing it. I think when you just open one file in your home folder, isn't there a way for VS Code to not also open the whole folder? But in general maybe we should just disable the language server if we detect that someone is opening the home folder...

No Idea, emacs projectile has the notion of projects, these are git/svn/... repositories or directories with a file `.projectile`.

**Comment by davidanthoff** [comment]
Yes, nothing we can do about the VS code repo, that is completely a MS thing.

Yes, just post the output buffer whenever something crashes. The one you posted was certainly due to you opening your home folder, I think at the end of the day we just don't support that right now. That is something we'll try to find a good fix for. But if you get more crashes, even when you open a folder that is not your home folder, please post here.

**Comment by davidanthoff** [comment]
I'm closing this for now, I don't think there is anything actionable here.
