### ISSUE TITLE
Typing a $ inside a docstring crashes language server

### ISSUE THREAD

**Issue by tkoolen** [JuliaEditorSupport/julia-vscode#273]
In an empty file (with Julia language mode), type
```julia
"""
"""
f(x) = x
```
Then insert a `$` into the docstring. Result:
```
ERROR: LoadError: Internal error
Stacktrace:
 [1] error_unexpected(::CSTParser.ParseState, ::Tokenize.Tokens.RawToken) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/hints.jl:99
 [2] INSTANCE(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/spec.jl:166
 [3] parse_string_or_cmd(::CSTParser.ParseState, ::Bool) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/components/strings.jl:121
 [4] CSTParser.LITERAL(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/spec.jl:80
 [5] parse_doc(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/CSTParser.jl:287
 [6] parse(::CSTParser.ParseState, ::Bool) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/CSTParser.jl:324
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:7
 [8] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/didOpen")},LanguageServer.DidOpenTextDocumentParams}, ::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:101
 [9] run(::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 12:34:31 PM] Connection to server got closed. Server will restart.
ERROR: LoadError: Internal error
Stacktrace:
 [1] error_unexpected(::CSTParser.ParseState, ::Tokenize.Tokens.RawToken) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/hints.jl:99
 [2] INSTANCE(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/spec.jl:166
 [3] parse_string_or_cmd(::CSTParser.ParseState, ::Bool) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/components/strings.jl:121
 [4] CSTParser.LITERAL(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/spec.jl:80
 [5] parse_doc(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/CSTParser.jl:287
 [6] parse(::CSTParser.ParseState, ::Bool) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/CSTParser.jl:324
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:7
 [8] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/didChange")},LanguageServer.DidChangeTextDocumentParams}, ::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:135
 [9] run(::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 12:34:44 PM] Connection to server got closed. Server will restart.
[Error - 12:34:44 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:178:36)
ERROR: LoadError: Internal error
Stacktrace:
 [1] error_unexpected(::CSTParser.ParseState, ::Tokenize.Tokens.RawToken) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/hints.jl:99
 [2] INSTANCE(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/spec.jl:166
 [3] parse_string_or_cmd(::CSTParser.ParseState, ::Bool) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/components/strings.jl:121
 [4] CSTParser.LITERAL(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/spec.jl:80
 [5] parse_doc(::CSTParser.ParseState) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/CSTParser.jl:287
 [6] parse(::CSTParser.ParseState, ::Bool) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/CSTParser/src/CSTParser.jl:324
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:7
 [8] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/didOpen")},LanguageServer.DidOpenTextDocumentParams}, ::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:101
 [9] run(::LanguageServer.LanguageServerInstance) at /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 12:34:50 PM] Connection to server got closed. Server will restart.
[Error - 12:34:50 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 12:34:50 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/twan/.vscode/extensions/julialang.language-julia-0.8.0-beta.1/node_modules/vscode-jsonrpc/lib/events.js:178:36) 
```

This is with 0.8.0-beta.1 installed from the .vsix.

**Comment by ZacLN** [comment]
Yep I'm on this, it's triple quotes only

**Comment by ZacLN** [comment]
[fix](https://github.com/ZacLN/CSTParser.jl/commit/1a7ad0214cec276ee73e81af0647927a1b470957)
