### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by pevnak** [JuliaEditorSupport/julia-vscode#299]
Hello,

I have installed the latest version of a plugin. I have used it happily for about two days and then it has started to emit error. I have restarted VS and tracked, when errors have started, which I have pasted below

```
INFO: parsed /Users/tpevny/Work/Julia/mil-jim/user/tfcode/variance.jl
ERROR: LoadError: LoadError: Package metadata directory /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/julia_pkgdir/v0.6/METADATA doesn't exist; run Pkg.init() to initialize it.
Stacktrace:
 [1] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:28
 [2] installed(::String) at ./pkg/pkg.jl:147
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Users/tpevny/.julia/v0.6/Knet/src/karray.jl, in expression starting on line 358
while loading /Users/tpevny/.julia/v0.6/Knet/src/Knet.jl, in expression starting on line 17
ERROR: LoadError: LoadError: Package metadata directory /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/julia_pkgdir/v0.6/METADATA doesn't exist; run Pkg.init() to initialize it.
Stacktrace:
 [1] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:28
 [2] installed(::String) at ./pkg/pkg.jl:147
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Users/tpevny/.julia/v0.6/Knet/src/karray.jl, in expression starting on line 358
while loading /Users/tpevny/.julia/v0.6/Knet/src/Knet.jl, in expression starting on line 17
ERROR: LoadError: TypeError: Expr: expected Symbol, got CSTParser.EXPR{CSTParser.Cell1d}
Stacktrace:
 [1] Expr(::Any) at ./boot.jl:192
 [2] get_t at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/CSTParser/src/scoping.jl:41 [inlined]
 [3] _add_sigarg(::CSTParser.BinarySyntaxOpCall, ::CSTParser.EXPR{CSTParser.Call}, ::LanguageServer.TopLevelScope, ::Set{String}) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/trav/local.jl:101
 [4] _fsig_scope(::CSTParser.WhereOpCall, ::LanguageServer.TopLevelScope, ::LanguageServer.LanguageServerInstance, ::Set{String}) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/trav/local.jl:92
 [5] lint(::CSTParser.EXPR{CSTParser.FunctionDef}, ::LanguageServer.TopLevelScope, ::LanguageServer.LintState, ::LanguageServer.LanguageServerInstance, ::Bool) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/trav/lint.jl:335
 [6] lint(::CSTParser.EXPR{CSTParser.FileH}, ::LanguageServer.TopLevelScope, ::LanguageServer.LintState, ::LanguageServer.LanguageServerInstance, ::Bool) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/trav/lint.jl:112
 [7] lint(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/trav/lint.jl:47
 [8] process(::LanguageServer.JSONRPC.Request{Val{Symbol("workspace/didChangeConfiguration")},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:204
 [9] run(::LanguageServer.LanguageServerInstance) at /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 14:26:01] Connection to server got closed. Server will restart.
[Error - 14:26:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/Users/tpevny/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 14:26:01] Request textDocument/documentLink failed.
```

I use Julia v0.6 on Mac with the latest stable version of VS.

**Comment by ZacLN** [comment]
There are two problems here:
1) The package (Knet) won't run when no METADATA pkgdir is defined.
2) something on the CSTParser side.

I've fixed the first (in terms of not repeatedly trying to load the module) but can't replicate the second yet

**Comment by davidanthoff** [comment]
@ZacLN do we still want to do something about this for 0.8.0, or move to the backlog?

**Comment by ZacLN** [comment]
Not much we can do at the moment with this, it's fixed in terms of crashing but you cant edit Knet, moving to backlog

**Comment by davidanthoff** [comment]
Closing as outdated: the language server now requires Julia 1.11 or newer (it refuses to start below that), so the configuration in this report is no longer supported. Juliaup, environment discovery and language server startup have all been reworked since as well.

If you hit something similar on a current setup, please open a new issue with the details and we will take a look.
