### ISSUE TITLE
Error when typing hex numbers

### ISSUE THREAD

**Issue by ssfrr** [JuliaEditorSupport/julia-vscode#311]
To reproduce, just open a new editor, set the file type to "julia" and type `0x`, as if you were about to type in a hex number.

This is the console log output:

```
ERROR: LoadError: ArgumentError: premature end of integer: "0x"
Stacktrace:
 [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:71
 [2] parse(::Type{Int64}, ::String) at ./parse.jl:184
 [3] Expr_int(::CSTParser.LITERAL) at /home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/CSTParser/src/conversion.jl:107
 [4] Expr(::CSTParser.LITERAL) at /home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/CSTParser/src/conversion.jl:75
 [5] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.TextDocumentPositionParams}, ::LanguageServer.LanguageServerInstance) at /home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/provider_completions.jl:86
 [6] run(::LanguageServer.LanguageServerInstance) at /home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [7] include_from_node1(::String) at ./loading.jl:569
 [8] include(::String) at ./sysimg.jl:14
 [9] process_options(::Base.JLOptions) at ./client.jl:305
 [10] _start() at ./client.jl:371
while loading /home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 2:01:36 AM] Connection to server got closed. Server will restart.
[Error - 2:01:36 AM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 2:01:36 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 2:01:36 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
[Error - 2:01:36 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:66:35)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1071:38)
	at LanguageClient.handleConnectionClosed (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/main.js:86:15)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-languageclient/lib/client.js:1059:18)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
	at closeHandler (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:114:39)
	at Emitter.fire (/home/sfr/.vscode/extensions/julialang.language-julia-0.8.0-beta.4/node_modules/vscode-jsonrpc/lib/events.js:178:36)
INFO: parsed /home/sfr/juliadev/WAV/src/WAV.jl
INFO: parsed /home/sfr/juliadev/WAV/src/companding.jl
INFO: parsed /home/sfr/juliadev/WAV/src/fileio.jl
INFO: parsed /home/sfr/juliadev/WAV/src/formats.jl
INFO: parsed /home/sfr/juliadev/WAV/test/reading.jl
INFO: parsed /home/sfr/juliadev/WAV/test/runtests.jl
```

**Comment by ZacLN** [comment]
fixed up stream, will be in next beta/release

**Comment by ssfrr** [comment]
Fantastic, thanks!
