### ISSUE TITLE
Precompiling user modules can leave the extension in a broken state

### ISSUE THREAD

**Issue by helgee** [JuliaEditorSupport/julia-vscode#315]
See below. It does not happen on macOS. I have not had time to look deeper into this or provide an MWE. Please let me know if you need anything else.

EDIT: This is the module: https://github.com/JuliaAstro/AstronomicalTime.jl

# Julia v0.6
```
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\docs\make.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\AstronomicalTime.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\constants.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\conversions.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\Epochs.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\LeapSeconds.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\Periods.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\src\TimeScales.jl
INFO: parsed c:\users\heichhorn\.julia\v0.6\astronomicaltime\test\runtests.jl

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x702fcba5 -- ZNK4llvm5Value7getNameEv at C:\Users\heichhorn\AppData\Local\Julia-0.6.0\bin\LLVM.dll (unknown line)
while loading C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\main.jl, in expression starting on line 27
ZNK4llvm5Value7getNameEv at C:\Users\heichhorn\AppData\Local\Julia-0.6.0\bin\LLVM.dll (unknown line)
jl_compile_linfo at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:1292
emit_invoke at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:3394 [inlined]
emit_expr at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:4129
emit_assignment at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:3753 [inlined]
emit_expr at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:4153
emit_stmtpos at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:4058 [inlined]
emit_function at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:6242
jl_compile_linfo at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\codegen.cpp:1256
jl_compile_for_dispatch at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1675
jl_compile_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:307 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:354 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1424 [inlined]
jl_module_run_initializer at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:87
jl_init_restored_modules at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\dump.c:2443 [inlined]
_jl_restore_incremental at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\dump.c:3272
jl_restore_incremental at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\dump.c:3292
_include_from_serialized at .\loading.jl:157
_require_from_serialized at .\loading.jl:200
unknown function (ip: 00000000099ED8BD)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
_require_search_from_serialized at .\loading.jl:236
unknown function (ip: 00000000099EF8ED)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
_require at .\loading.jl:434
require at .\loading.jl:398
unknown function (ip: 00000000099EA256)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1424 [inlined]
eval_import_path_ at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:403
eval_import_path at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:430 [inlined]
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:510
jl_toplevel_eval_in at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:496
import_modules at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\trav\toplevel.jl:153
unknown function (ip: 00000000099E5AC2)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
import_modules at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\trav\toplevel.jl:128
toplevel_symbols at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\trav\toplevel.jl:121
unknown function (ip: 00000000099E1592)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
toplevel at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\trav\toplevel.jl:32
unknown function (ip: 00000000099E1172)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
lint at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\trav\lint.jl:41
process at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\provider_misc.jl:204
unknown function (ip: 00000000099E02CA)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
run at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:35
unknown function (ip: 0000000009966B46)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
do_call at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:75
eval at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:242
jl_interpret_toplevel_expr at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\interpreter.c:34
jl_toplevel_eval_flex at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:577
jl_parse_eval_all at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\ast.c:873
jl_load at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:616 [inlined]
jl_load_ at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:623
include_from_node1 at .\loading.jl:569
unknown function (ip: 0000000061CD2571)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
include at .\sysimg.jl:14
unknown function (ip: 0000000061B43F41)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
process_options at .\client.jl:305
_start at .\client.jl:371
unknown function (ip: 0000000061CDF45E)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1424 [inlined]
true_main at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:127
wmain at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:264
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.2-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.2-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 12239433 (Pool: 12237248; Big: 2185); GC: 25
[Info  - 16:56:26] Connection to server got closed. Server will restart.
[Error - 16:56:26] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\main.js:816:25)
	at Object.dispose (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\client.js:66:35)
	at LanguageClient.handleConnectionClosed (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\client.js:1071:38)
	at LanguageClient.handleConnectionClosed (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\main.js:86:15)
	at closeHandler (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\client.js:1059:18)
	at CallbackList.invoke (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:178:36)
	at closeHandler (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\main.js:212:26)
	at CallbackList.invoke (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:178:36)
[Error - 16:56:26] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\main.js:816:25)
	at Object.dispose (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\client.js:66:35)
	at LanguageClient.handleConnectionClosed (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\client.js:1071:38)
	at LanguageClient.handleConnectionClosed (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\main.js:86:15)
	at closeHandler (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-languageclient\lib\client.js:1059:18)
	at CallbackList.invoke (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:178:36)
	at closeHandler (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\main.js:212:26)
	at CallbackList.invoke (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\node_modules\vscode-jsonrpc\lib\events.js:178:36)
```

# Julia v0.7-nightly
```

WARNING: deprecated syntax "immutable" at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\AbstractTrees\src\AbstractTrees.jl:61.
Use "struct" instead.
ERROR: LoadError: syntax: invalid escape sequence
Stacktrace:
 [1] include_relative(::Module, ::String) at .\loading.jl:533
 [2] include(::Module, ::String) at .\sysimg.jl:14
 [3] anonymous at .\<missing>:2
in expression starting at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\AbstractTrees\src\AbstractTrees.jl:111
ERROR: LoadError: Failed to precompile AbstractTrees to C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\julia_pkgdir\lib\v0.7\AbstractTrees.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:661
 [2] _require(::Symbol) at .\loading.jl:450
 [3] require(::Symbol) at .\loading.jl:324
 [4] include_relative(::Module, ::String) at .\loading.jl:533
 [5] include(::Module, ::String) at .\sysimg.jl:14
 [6] anonymous at .\<missing>:2
in expression starting at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\CSTParser\src\CSTParser.jl:6
ERROR: LoadError: Failed to precompile CSTParser to C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\julia_pkgdir\lib\v0.7\CSTParser.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:661
 [2] _require(::Symbol) at .\loading.jl:450
 [3] require(::Symbol) at .\loading.jl:324
 [4] include_relative(::Module, ::String) at .\loading.jl:533
 [5] include(::Module, ::String) at .\sysimg.jl:14
 [6] anonymous at .\<missing>:2
in expression starting at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\DocumentFormat\src\DocumentFormat.jl:2
ERROR: LoadError: Failed to precompile DocumentFormat to C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\julia_pkgdir\lib\v0.7\DocumentFormat.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:661
 [2] _require(::Symbol) at .\loading.jl:450
 [3] require(::Symbol) at .\loading.jl:324
 [4] include_relative(::Module, ::String) at .\loading.jl:533
 [5] include(::Module, ::String) at .\sysimg.jl:14
 [6] anonymous at .\<missing>:2
in expression starting at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\packages\LanguageServer\src\LanguageServer.jl:5
ERROR: LoadError: Failed to precompile LanguageServer to C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\julia_pkgdir\lib\v0.7\LanguageServer.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:661
 [2] _require(::Symbol) at .\loading.jl:472
 [3] require(::Symbol) at .\loading.jl:324
 [4] include_relative(::Module, ::String) at .\loading.jl:533
 [5] include(::Module, ::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:325
 [7] _start() at .\client.jl:391
in expression starting at C:\Users\heichhorn\.vscode\extensions\julialang.language-julia-0.8.0-beta.4\scripts\languageserver\main.jl:24
[Info  - 17:03:17] Connection to server got closed. Server will restart.
```

**Comment by ZacLN** [comment]
I can't replicate this on linux, could you try: 
```
using CSTParser
str = readstring("c:\users\heichhorn\.julia\v0.6\astronomicaltime\test\runtests.jl")
CSTParser.parse(str, true)
```
and see if it segfaults?

**Comment by helgee** [comment]
Nope. That works.

**Comment by helgee** [comment]
I will check what happens on 0.6.1 later today.

**Comment by helgee** [comment]
The segfault is gone on 0.6.1. I assume this can be closed.

**Comment by helgee** [comment]
And its back...

**Comment by ZacLN** [comment]
Can you try https://gist.github.com/ZacLN/2ea80a0ad7135b9f196159d851d3f1d1

**Comment by helgee** [comment]
```
WARNING: ignoring conflicting import of LanguageServer.eval into Main
WARNING: imported binding for Range overwritten in module Main
ERROR: LoadError: Invalid escape sequence
Line: 0
Around: ...ath":"C:\Users\heichhorn\.juli...
                    ^

Stacktrace:
 [1] _error(::String, ::JSON.Parser.MemoryParserState) at C:\Users\heichhorn\.ju                                                                                                               lia\v0.6\JSON\src\Parser.jl:131
 [2] parse_string(::JSON.Parser.MemoryParserState, ::Array{UInt8,1}) at C:\Users                                                                                                               \heichhorn\.julia\v0.6\JSON\src\specialized.jl:109
 [3] parse_string(::JSON.Parser.MemoryParserState) at C:\Users\heichhorn\.julia\                                                                                                               v0.6\JSON\src\specialized.jl:18
 [4] parse_value(::JSON.Parser.MemoryParserState, ::Type{T} where T) at C:\Users                                                                                                               \heichhorn\.julia\v0.6\JSON\src\Parser.jl:153
 [5] parse_object(::JSON.Parser.MemoryParserState, ::Type{T} where T) at C:\User                                                                                                               s\heichhorn\.julia\v0.6\JSON\src\Parser.jl:214
 [6] parse_value(::JSON.Parser.MemoryParserState, ::Type{T} where T) at C:\Users                                                                                                               \heichhorn\.julia\v0.6\JSON\src\Parser.jl:157
 [7] parse_object(::JSON.Parser.MemoryParserState, ::Type{T} where T) at C:\User                                                                                                               s\heichhorn\.julia\v0.6\JSON\src\Parser.jl:214
 [8] parse_value(::JSON.Parser.MemoryParserState, ::Type{T} where T) at C:\Users                                                                                                               \heichhorn\.julia\v0.6\JSON\src\Parser.jl:157
 [9] #parse#1(::Type{Dict{String,Any}}, ::Function, ::String) at C:\Users\heichh                                                                                                               orn\.julia\v0.6\JSON\src\Parser.jl:374
 [10] parse(::Type{LanguageServer.JSONRPC.Request}, ::String) at C:\Users\heichh                                                                                                               orn\.julia\v0.6\LanguageServer\src\jsonrpc.jl:31
 [11] include_from_node1(::String) at .\loading.jl:576
 [12] include(::String) at .\sysimg.jl:14
 [13] process_options(::Base.JLOptions) at .\client.jl:305
 [14] _start() at .\client.jl:371
while loading C:\Users\heichhorn\Downloads\debug.jl, in expression starting on l                                                                                                               ine 15
```

**Comment by ZacLN** [comment]
Erg, @davidanthoff could you see if this happens on your windows set up?

**Comment by davidanthoff** [comment]
So I just opened AstronomicalTime (current ``master``) on Windows with the latest master version of our extension. I did run into a number of problems:
- AstronomicalTime relies on a very recent version of Compat. The LS process will always use the Compat version that we ship as part of the extension, and we currently shipped a somewhat older version... I now updated version that we ship, but the solution to this of course is to not load user packages into the LS process, but instead have a second process that does all user package loading, which relies purely on the packages in ``.julia``, i.e. for which we don't change anything about LOAD_PATH.
- Even with an up-to-date Compat.jl version I see errors that I think related to the same upper-lower-case problems about includes that we/I have seen with other packages on Windows. I'll try to dig into that one, it seems quite important.

I did not see any crashes, or segfaults, though... This is on julia 0.6.0.

**Comment by ZacLN** [comment]
Cheers, I'm completely bemused by this case issue

**Comment by helgee** [comment]
I also cannot reproduce it anymore 😕

**Comment by davidanthoff** [comment]
I'll close this for now, the original bug seems to be sorted out.

**Comment by helgee** [comment]
After installing RC7 the problem is back, this time also with another package of mine (AstroDynBase, although that one depends on AstronomicalTime). Since this seems to be an upstream issue, this is probably not release-blocking for you.

I will try to reproduce the issue on my home machine tonight and come up with an MWE.

**Comment by davidanthoff** [comment]
Alright, I just opened that package on my system and so far nothing crashes. I'd say we fix this in the next version. Thanks for following up!

**Comment by helgee** [comment]
@davidanthoff Which Windows version are you running?

Since I am (again) unable to reproduce this at home, it must have something to do with my work machine, which is stuck at Windows 10 1607.

**Comment by davidanthoff** [comment]
I'm on the latest Win10, whatever that is :)

**Comment by helgee** [comment]
Well, I have just ruled out that theory. I will try to get hold of another machine at work tomorrow and see whether it is the environment or my particular device.

Let's see how deep this rabbit hole goes 😉

**Comment by helgee** [comment]
Not that deep after all...

The difference between my work machine and the others was that I had precompilation switched on there and did not commit the change. Sorry about the confusion. It crashes now consistenly on every Windows machine 😛 

The good news is that this does not occur 0.7. I really wonder though, why does the language server precompile user modules?

**Comment by ZacLN** [comment]
At the moment we have to load modules to access symbols/locations of code etc. into the server process and we keep a separate pkg_dir so that we don't interfere with the users main pkg_dir

**Comment by helgee** [comment]
The problem was this method:
```julia
Base.show(io::IO, ::Type{T}) where {T<:TimeScale} = print(io, T.name.name)
```
While doing this is considered harmful (https://github.com/JuliaLang/julia/issues/24195), the problem was excacerbated by the way the VS code extension currently works.

When the offending method is present the first time the package is opened in VS Code and then precompiled, the language server will crash on every subsequent attempt to parse the package. Commenting it out does not help. One needs to manually remove the *.ji file in `julia_pkgdir` or trigger a recompilation in another way. Who is deciding when a recompilation is happening, base julia or the language server?

This leaves the extension in a broken state for the specific package. Due to this I think that user code should probably be precompiled unconditionally or not precompiled at all. Is that possible?

**Comment by davidanthoff** [comment]
I'm going to close this for now. We know the fix for this: move loading of user code out of the language server process. I've started working on that, but it won't ship in v0.10.0. I don't think there is anything else we can do to mitigate this for now.

**Comment by helgee** [comment]
Looking forward to it. Thanks for your work on the extension!
