### ISSUE TITLE
Code that crashes the LS

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#341]
Open a folder with a single file in it with the following content:
````julia
include("TEST1.jl"j
println("test")
````
This crashes the LS with the following error:
````
INFO: parsed c:\Users\david\Desktop\repo2\test.jl
INFO: 2,1-2,7          IDENTIFIER     
ERROR: LoadError: Internal error
Stacktrace:
 [1] error_unexpected(::CSTParser.ParseState, ::Tokenize.Tokens.RawToken) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\hints.jl:106
 [2] parse_call(::CSTParser.ParseState, ::Any) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\components\functions.jl:109
 [3] macro expansion at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\utils.jl:54 [inlined]
 [4] parse_compound(::CSTParser.ParseState, ::Any) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\CSTParser.jl:186
 [5] macro expansion at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\utils.jl:179 [inlined]
 [6] parse_expression(::CSTParser.ParseState) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\CSTParser.jl:88
 [7] parse_doc(::CSTParser.ParseState) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\CSTParser.jl:303
 [8] parse(::CSTParser.ParseState, ::Bool) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\CSTParser\src\CSTParser.jl:324
 [9] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\provider_diagnostics.jl:7
 [10] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\provider_misc.jl:66
 [11] run(::LanguageServer.LanguageServerInstance) at c:\Users\david\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:35
 [12] include_from_node1(::String) at .\loading.jl:569
 [13] include(::String) at .\sysimg.jl:14
 [14] process_options(::Base.JLOptions) at .\client.jl:305
 [15] _start() at .\client.jl:371
while loading c:\Users\david\source\julia-vscode\scripts\languageserver\main.jl, in expression starting on line 27
[Info  - 4:35:29 PM] Connection to server got closed. Server will restart.
[Error - 4:35:29 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\main.js:816:25)
	at Object.dispose (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\client.js:66:35)
	at LanguageClient.handleConnectionClosed (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\client.js:1071:38)
	at LanguageClient.handleConnectionClosed (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\main.js:86:15)
	at closeHandler (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\client.js:1059:18)
	at CallbackList.invoke (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:178:36)
	at closeHandler (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\main.js:212:26)
	at CallbackList.invoke (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:178:36)
[Error - 4:35:29 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\main.js:816:25)
	at Object.dispose (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\client.js:66:35)
	at LanguageClient.handleConnectionClosed (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\client.js:1071:38)
	at LanguageClient.handleConnectionClosed (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\main.js:86:15)
	at closeHandler (c:\Users\david\source\julia-vscode\node_modules\vscode-languageclient\lib\client.js:1059:18)
	at CallbackList.invoke (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:178:36)
	at closeHandler (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\main.js:212:26)
	at CallbackList.invoke (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:114:39)
	at Emitter.fire (c:\Users\david\source\julia-vscode\node_modules\vscode-jsonrpc\lib\events.js:178:36)
````

**Comment by ZacLN** [comment]
Got it: https://github.com/ZacLN/CSTParser.jl/commit/2af67c11e7378d6b716766ba347dd9920e971d59
