### ISSUE TITLE
Execute block doesn't work initially

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#359]
From @malmaud:

> on that rc, when i open a julia buffer, I see ‘Julia’ in red at the bottom-left for ~20  seconds, and if i try to execute code during that time, i see ’Running the contributed command:‘language-julia.executeJuliaBlockInREPL’ failed.' then if i try again, i see
````
[Error - 12:44:59] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-jsonrpc/lib/main.js:818:25)
    at Object.dispose (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-languageclient/lib/client.js:57:35)
    at LanguageClient.handleConnectionClosed (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-languageclient/lib/client.js:1864:38)
    at LanguageClient.handleConnectionClosed (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-languageclient/lib/main.js:78:15)
    at closeHandler (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-languageclient/lib/client.js:1852:18)
    at CallbackList.invoke (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-jsonrpc/lib/main.js:214:26)
    at CallbackList.invoke (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/malmaud/.vscode/extensions/julialang.language-julia-0.8.0-rc.2/node_modules/vscode-jsonrpc/lib/events.js:135:36)
````

**Comment by davidanthoff** [comment]
Fixed in #360.
