### ISSUE TITLE
Language server crash if the file path contains spaces

### ISSUE THREAD

**Issue by essenciary** [JuliaEditorSupport/julia-vscode#393]
For the last few weeks I've been using a beta of 0.8.0 in order to avoid the "julia Language Server server crashed" problem in v0.7. 

It seems that with the recent release of v0.8.0, VSCode updated the extension. And now sadly, the problem is back. 

"The julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

**Comment by KristofferC** [comment]
I think you need to provide some debug output to get help. What does it say in the Output tab?

**Comment by essenciary** [comment]
Sure. Here it is: 

```
[Error - 15:30:53] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
[Error - 15:30:53] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Articles.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Database.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/GameSession.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Gameplay.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/WebApp.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Wikipedia.jl
ERROR: LoadError: Path contained unexpected character
Stacktrace:
 [1] parse_url(::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/URIParser/src/parser.jl:261
 [2] uri2filepath at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:176 [inlined]
 [3] joinuriwithpath(::String, ::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:199
 [4] (::LanguageServer.##55#56{LanguageServer.Document})(::Tuple{String,Array{Any,1}}) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:42
 [5] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},LanguageServer.##55#56{LanguageServer.Document}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:454
 [6] update_includes(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:41
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:9
 [8] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:66
 [9] run(::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 15:31:03] Connection to server got closed. Server will restart.
[Error - 15:31:03] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
[Error - 15:31:03] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Articles.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Database.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/GameSession.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Gameplay.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/WebApp.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Wikipedia.jl
ERROR: LoadError: Path contained unexpected character
Stacktrace:
 [1] parse_url(::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/URIParser/src/parser.jl:261
 [2] uri2filepath at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:176 [inlined]
 [3] joinuriwithpath(::String, ::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:199
 [4] (::LanguageServer.##55#56{LanguageServer.Document})(::Tuple{String,Array{Any,1}}) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:42
 [5] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},LanguageServer.##55#56{LanguageServer.Document}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:454
 [6] update_includes(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:41
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:9
 [8] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:66
 [9] run(::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 15:31:13] Connection to server got closed. Server will restart.
[Error - 15:31:13] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
[Error - 15:31:13] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Articles.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Database.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/GameSession.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Gameplay.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/WebApp.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Wikipedia.jl
ERROR: LoadError: Path contained unexpected character
Stacktrace:
 [1] parse_url(::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/URIParser/src/parser.jl:261
 [2] uri2filepath at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:176 [inlined]
 [3] joinuriwithpath(::String, ::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:199
 [4] (::LanguageServer.##55#56{LanguageServer.Document})(::Tuple{String,Array{Any,1}}) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:42
 [5] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},LanguageServer.##55#56{LanguageServer.Document}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:454
 [6] update_includes(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:41
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:9
 [8] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:66
 [9] run(::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/main.jl, in expression starting on line 27
[Info  - 15:31:22] Connection to server got closed. Server will restart.
[Error - 15:31:22] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
[Error - 15:31:22] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Articles.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Database.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/GameSession.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Gameplay.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/WebApp.jl
INFO: parsed /Users/adrian/Dropbox/Projects/Julia v1.0 By Example/chapter_5_examples/sixdegrees/Wikipedia.jl
ERROR: LoadError: Path contained unexpected character
Stacktrace:
 [1] parse_url(::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/URIParser/src/parser.jl:261
 [2] uri2filepath at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:176 [inlined]
 [3] joinuriwithpath(::String, ::String) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/utilities.jl:199
 [4] (::LanguageServer.##55#56{LanguageServer.Document})(::Tuple{String,Array{Any,1}}) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:42
 [5] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},LanguageServer.##55#56{LanguageServer.Document}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:454
 [6] update_includes(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:41
 [7] parse_all(::LanguageServer.Document, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_diagnostics.jl:9
 [8] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/provider_misc.jl:66
 [9] run(::LanguageServer.LanguageServerInstance) at /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [10] include_from_node1(::String) at ./loading.jl:569
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/scripts/languageserver/main.jl, in expression starting on line 27
[Error - 15:31:31] Connection to server got closed. Server will not be restarted.
[Error - 15:31:31] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
[Error - 15:31:31] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/adrian/.vscode/extensions/julialang.language-julia-0.8.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
```

**Comment by essenciary** [comment]
Huhm... could it be the path with spaces?

**Comment by essenciary** [comment]
Yup, it seems that having a space anywhere in the path causes the issue.

**Comment by KristofferC** [comment]
Yes,

```
julia> URIParser.is_url_char(' ')
false
```

**Comment by essenciary** [comment]
I've updated the title to reflect the new findings - hopefully it's nothing major, the beta worked beautifully.

**Comment by davidanthoff** [comment]
@essenciary We'll have a release candidate for v0.8.1 out soon, would be great if you could give that one a spin to see whether we actually fixed this or not.

**Comment by essenciary** [comment]
@davidanthoff Absolutely!

**Comment by davidanthoff** [comment]
@essenciary Can you try this version: https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.8.1-rc.1? I think it should fix this bug, but I can't test it on my system. I think this should fix a bug on non-Windows, and I'm on Windows. Thanks!

I'll reopen this issue and we'll close it once you report back that things work.

**Comment by davidanthoff** [comment]
@essenciary Any chance you could give the latest RC (https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.8.1-rc.2) a go and see whether that fixes the issue you reported? We are keen to release a bug fix release!

**Comment by davidanthoff** [comment]
We think this is fixed now. If not, please reopen.

**Comment by essenciary** [comment]
@davidanthoff Sorry, Too Damn Many GitHub notifications! 
I can confirm that all works great in RC2, thanks!

**Comment by davidanthoff** [comment]
Great, thanks!
