### ISSUE TITLE
no method matching convert(::Type{AssertionError}, ::String)

### ISSUE THREAD

**Issue by staticfloat** [JuliaEditorSupport/julia-vscode#421]
This happens intermittently as I'm editing my Large Julia Codebase (TM).  Sometimes it happens repeatedly so often that VSCode will tell me it's disabling the Julia language server.

```
ERROR: LoadError: MethodError: no method matching convert(::Type{AssertionError}, ::String)
Closest candidates are:
  convert(!Matched::Type{Any}, ::ANY) at essentials.jl:28
  convert(::Type{T}, !Matched::T) where T at essentials.jl:29
Stacktrace:
 [1] AssertionError(::String) at ./coreimg.jl:14
 [2] update_valid_age!(::UInt64, ::UInt64, ::Core.Inference.InferenceState) at ./inference.jl:2353
 [3] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1431
 [4] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [5] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [6] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [7] (::Core.Inference.##191#192{Array{Any,1},Core.Inference.InferenceState})(::Expr) at ./<missing>:0
 [8] next(::Core.Inference.Generator{Array{Any,1},Core.Inference.##191#192{Array{Any,1},Core.Inference.InferenceState}}, ::Int64) at ./generator.jl:45
 [9] copy!(::Array{Any,1}, ::Core.Inference.Generator{Array{Any,1},Core.Inference.##191#192{Array{Any,1},Core.Inference.InferenceState}}) at ./abstractarray.jl:573
 [10] _collect(::Type{Any}, ::Core.Inference.Generator{Array{Any,1},Core.Inference.##191#192{Array{Any,1},Core.Inference.InferenceState}}, ::Core.Inference.HasShape) at ./array.jl:396
 [11] collect(::Type{Any}, ::Core.Inference.Generator{Array{Any,1},Core.Inference.##191#192{Array{Any,1},Core.Inference.InferenceState}}) at ./array.jl:393
 [12] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1901
 [13] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [14] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2076
 [15] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669
 [16] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787
 [17] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [18] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [19] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [20] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [21] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [22] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722
 [23] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787
 [24] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [25] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [26] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [27] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [28] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [29] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2076
 [30] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669
 [31] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787
 [32] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [33] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [34] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [35] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [36] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [37] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722
 [38] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787
 [39] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [40] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [41] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [42] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [43] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [44] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2084
 [45] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669
 [46] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787
 [47] typeinf_frame(::Core.MethodInstance, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2504
 [48] typeinf_code(::Core.MethodInstance, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2583
 [49] typeinf_ext(::Core.MethodInstance, ::UInt64) at ./inference.jl:2622
 [50] plain(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Array{Any,1}) at ./markdown/render/plain.jl:11
 [51] plain(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Base.Markdown.MD) at ./markdown/render/plain.jl:14
 [52] plain(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Array{Any,1}) at ./markdown/render/plain.jl:11
 [53] print(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Base.Markdown.MD) at ./strings/io.jl:29
 [54] #print_to_string#231(::Void, ::Function, ::Base.Markdown.MD, ::Vararg{Base.Markdown.MD,N} where N) at ./strings/io.jl:102
 [55] string(::Base.Markdown.MD) at ./strings/io.jl:120
 [56] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.TextDocumentPositionParams}, ::LanguageServer.LanguageServerInstance) at /home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/scripts/languageserver/packages/LanguageServer/src/provider_completions.jl:72
 [57] run(::LanguageServer.LanguageServerInstance) at /home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:35
 [58] include_from_node1(::String) at ./loading.jl:576
 [59] include(::String) at ./sysimg.jl:14
 [60] process_options(::Base.JLOptions) at ./client.jl:305
 [61] _start() at ./client.jl:371
while loading /home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/scripts/languageserver/main.jl, in expression starting on line 27
```

It is followed by messages such as these, which I assume are not of interest to you:
```
[Info  - 12:59:28 PM] Connection to server got closed. Server will restart.
[Error - 12:59:28 PM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/home/sabae/.vscode/extensions/julialang.language-julia-0.8.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
```
And many other messages about requests such as `textDocument/signatureHelp`, `textDocument/codeAction`, etc...

**Comment by ZacLN** [comment]
Hmm I can add a quick and dirty fix for this but that stack trace has me confused, any clues as to the context of the completion when this error hits?

**Comment by staticfloat** [comment]
It just happens while I'm typing; I don't remember any other specifics, sorry.  I'll try to notice next time it happens.

**Comment by ZacLN** [comment]
The second set of messages are just a result of the server crashing. If you have the server logging turned on the request immediately before the stacktrace will tell you which file + line/col is causing the error

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/works-in-atom-juno-not-in-repl/7534

**Comment by davidanthoff** [comment]
@ZacLN any idea what we should do about this?

**Comment by ZacLN** [comment]
[this](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/245) for now
