### ISSUE TITLE
Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by MFairley** [JuliaEditorSupport/julia-vscode#474]
I'm getting the following errors popping up in the Output window and some functions from some imported modules are causing the Linter to give undeclared variable warnings e.g. all the functions and macros from JuMP.

`[Error - 12:44:27] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at LanguageClient.handleConnectionClosed (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
INFO: Set(String["/Users/mfairley/Source/mse348"])
INFO: parsed /Users/mfairley/Source/mse348/exponential_portfolio.jl
INFO: parsed /Users/mfairley/Source/mse348/main.jl
INFO: parsed /Users/mfairley/Source/mse348/sdp.jl
ERROR: LoadError: UndefVarError: Random not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/Rmath/src/Rmath.jl, in expression starting on line 9
ERROR: LoadError: LoadError: Failed to precompile Rmath to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/Rmath.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] include(::String) at ./sysimg.jl:14
 [8] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/StatsFuns/src/rmath.jl, in expression starting on line 6
while loading /Users/mfairley/.julia/v0.6/StatsFuns/src/StatsFuns.jl, in expression starting on line 228
ERROR: LoadError: Failed to precompile StatsFuns to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/StatsFuns.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/Distributions/src/Distributions.jl, in expression starting on line 6
ERROR: LoadError: UndefVarError: Random not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/ForwardDiff/src/ForwardDiff.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile ForwardDiff to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/ForwardDiff.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/ReverseDiffSparse/src/ReverseDiffSparse.jl, in expression starting on line 4
ERROR: LoadError: Failed to precompile ReverseDiffSparse to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/ReverseDiffSparse.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/JuMP/src/JuMP.jl, in expression starting on line 21
ERROR: LoadError: UndefVarError: isabstracttype not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/ColorTypes/src/ColorTypes.jl, in expression starting on line 10
ERROR: LoadError: Failed to precompile ColorTypes to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/ColorTypes.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/Colors/src/Colors.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Colors to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/Colors.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/PlotUtils/src/PlotUtils.jl, in expression starting on line 7
ERROR: LoadError: Failed to precompile PlotUtils to /Users/mfairley/.vscode/extensions/julialang.language-julia-0.9.1/scripts/languageserver/julia_pkgdir/lib/v0.6/PlotUtils.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/mfairley/.julia/v0.6/Plots/src/Plots.jl, in expression starting on line 13`

**Comment by davidanthoff** [comment]
This looks like a quite outdated version of the extension, could you update to the latest version of the extension? If this error still appears, please reopen this issue here.
