### ISSUE TITLE
"Julia Language Server is busy"... forever

### ISSUE THREAD

**Issue by habemus-papadum** [JuliaEditorSupport/julia-vscode#487]
Hi!  I was interested in trying julia-vscode 
(I'm on mac -- with up-to-date versions of vscode, julia, julia-vscode asof 5/1/18)

I've set my julia executable, and can start a repl fine from within vscode.
However,  within a `.jl` file, none of the intellisense features are working, and the bottom status bar permanently reports "Julia Language Server is busy"

To debug, I tried forcing `const global ls_debug_mode = true` in `main.jl` but I'm not seeing any Output (under "Output->Extensions", Output->Log(*)" etc)

Can you suggest some other things for me to try to debug and  figure out what's going on?

Thanks! nehal

**Comment by habemus-papadum** [comment]
toggling "developer tools", I see the following errors:

```
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
mainThreadExtensionService.ts:44 Error: Channel has been closed
        at e.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:521:747)
        at e.append (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:521:286)
        at Socket.serverProcess.stderr.on.data (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/main.js:332:72)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)
        at readableAddChunk (_stream_readable.js:178:18)
        at Socket.Readable.push (_stream_readable.js:136:10)
        at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
console.ts:136 [Extension Host] Error: Channel has been closed
        at e.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:521:747)
        at e.appendLine (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:521:381)
        at LanguageClient.info (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/client.js:1574:28)
        at LanguageClient.handleConnectionClosed (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/client.js:1875:18)
        at LanguageClient.handleConnectionClosed (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/main.js:106:15)
        at closeHandler (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-languageclient/lib/client.js:1852:18)
        at CallbackList.invoke (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
        at Emitter.fire (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
        at closeHandler (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/main.js:221:26)
        at CallbackList.invoke (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:71:39)
        at Emitter.fire (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/events.js:135:36)
        at StreamMessageWriter.AbstractMessageWriter.fireClose (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:57:27)
        at Socket.<anonymous> (/Users/nehal/src/lilinjn/liljulia/tmp/tmp3/.liljulia/.code/extensions/julialang.language-julia-0.9.1/node_modules/vscode-jsonrpc/lib/messageWriter.js:79:63)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)
        at Pipe._handle.close [as _onclose] (net.js:510:12)
t.log @ console.ts:136
```

I believe the issue might be related to the fact that my "julia" executable is a bash shell that sets up a few JULIA_* env variables and then launches julia -- does that make sense?

**Comment by habemus-papadum** [comment]
the issue ended up being that my bash script (when launched for the langserver, but not the repl) is launched in a simplified environment with a limited PATH -- which was leading my script to die, but in a way that was difficult to debug.   This is a variant of the warning that is given to mac users in the readme.  anyway, easy to work around, so now I'm a happy camper!  cheers, nehal
