### ISSUE TITLE
`Overlapping ranges are not allowed` error when trying to refactor variable names in a large file

### ISSUE THREAD

**Issue by x-ji** [JuliaEditorSupport/julia-vscode#609]
When I try to refactor variable names with F2, I get the error `Overlapping ranges are not allowed!` on hitting enter.

I think this has something to do with the nature of the file I'm editing. If I edit a simple file the refactor works fine.

Not sure if it's a bug from vscode or from this plugin.

- vscode: 1.29.1
- Julia: 1.0.2
- julia-vscode: j1.0alpha7

I'll try to see if I can produce a minimum example. The file is big.

```
[2018-11-24 17:39:10.971] [renderer1] [error] Error: Overlapping ranges are not allowed!
    at e.applyEdits (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:612:24)
    at o._applyEdits (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:1195:51)
    at o.applyEdits (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:1194:530)
    at e.pushEditOperation (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:556:398)
    at o._pushEditOperations (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:1194:365)
    at o.pushEditOperations (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:1193:152)
    at t.executeEdits (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:1928:590)
    at t.apply (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:4220:961)
    at e.apply (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:4222:490)
    at e.<anonymous> (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:4225:833)
    at file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:176:439
    at Object.o.__generator.a.label [as next] (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:176:544)
    at s (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:175:519)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by x-ji** [comment]
Just realized that there's a beta 2 release. But the bug persists.

**Comment by ZacLN** [comment]
This should be straightforward to fix but a mwe would really help

**Comment by davidanthoff** [comment]
I'm closing for now because we don't have enough information to do anything about this. @x-ji if you have time to provide follow up information, please do and reopen this issue!

**Comment by x-ji** [comment]
Sure. I think I haven't been seeing this in a while. If I see it happening again I'll try to produce a mwe.
